dist: trusty
language: go
go:
  - 1.10.x
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sqlxtest;'
  - psql -c 'create database sqlxtest;' -U postgres
  - export SQLX_MYSQL_DSN="travis:@/sqlxtest?parseTime=true"
  - export SQLX_POSTGRES_DSN="postgres://postgres:@localhost/sqlxtest?sslmode=disable"
  - export SQLX_SQLITE_DSN="$HOME/sqlxtest.db"
script:
  - go test -test.bench=.* -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
